# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d144ed76d26807384515beb9de63253bd78db8bab4e5889fce610fa243e7359b61b53c213f4f1ae3cb79d56cbb2bfdbdfffb7e1f2a4b6d260301644ba86ad73

test:
  secret_key_base: 822a82faaff15541b0b3b65d50a3536e6dba0c663c9db7f19cb6300e044a15ab39c1411c958befc2002582a06c1006082f0826f2c225f3eaeb87db3b2c06ee45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
